### ISSUE TITLE
Error on Project Run

### ISSUE THREAD

**Issue by TRexStark** [limbo-works/Limbo.Umbraco.Vimeo#1]
Hi @abjerner 

Latest Umbraco 10 with the package 2.0.0-alpha001 is throwing an error when trying to run the project

![Screenshot 2022-12-01 at 1 11 05 am](https://user-images.githubusercontent.com/70106895/204817943-02894c8c-b630-4d6a-bf1c-4947d1f6f2ab.png)

Hit me up on Slack if you need me to provide more details.

**Comment by abjerner** [comment]
I had to make a breaking change in an underlying package. I were working on updating the Vimeo package earlier today - I hope to wrap that up later today and push a new release.

**Comment by TRexStark** [comment]
Thanks @abjerner for the prompt response. Looking forward to it.

**Comment by abjerner** [comment]
Just out of curiosity, have you also installed our YouTube package? I think that may be why, as the YouTube package has been updated to use the new dependency, but the Vimeo package hasn't. Installing just the Vimeo package should work.

Anyways, new release will be out soon 😉

**Comment by abjerner** [comment]
Hi again @TRexStark 

I've new pushed a new release, which also contains a few bug fixes and general improvements:

https://github.com/limbo-works/Limbo.Umbraco.Vimeo/releases/tag/v2.0.0

**Comment by TRexStark** [comment]
Hi @abjerner sorry for the late reply... Yes I have the YouTube one installed as well.

I will try the new release and come back to you.
